//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactrIDE.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FactrIDE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency.
        /// </summary>
        internal static string AddDependencyToProjectText {
            get {
                return ResourceManager.GetString("AddDependencyToProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Modification.
        /// </summary>
        internal static string AddExistingFactorioProjectToSolutionExplorerText {
            get {
                return ResourceManager.GetString("AddExistingFactorioProjectToSolutionExplorerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing File.
        /// </summary>
        internal static string AddExistingFileToProjectText {
            get {
                return ResourceManager.GetString("AddExistingFileToProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Folder.
        /// </summary>
        internal static string AddExistingFolderToProjectText {
            get {
                return ResourceManager.GetString("AddExistingFolderToProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Modification.
        /// </summary>
        internal static string AddNewFactorioProjectToSolutionExplorerText {
            get {
                return ResourceManager.GetString("AddNewFactorioProjectToSolutionExplorerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Folder.
        /// </summary>
        internal static string AddNewFolderToProjectText {
            get {
                return ResourceManager.GetString("AddNewFolderToProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Localization.
        /// </summary>
        internal static string AddNewLocalizationFileToProjectText {
            get {
                return ResourceManager.GetString("AddNewLocalizationFileToProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Lua.
        /// </summary>
        internal static string AddNewLuaFileToProjectText {
            get {
                return ResourceManager.GetString("AddNewLuaFileToProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string ButtonBrowse {
            get {
                return ResourceManager.GetString("ButtonBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ButtonOK {
            get {
                return ResourceManager.GetString("ButtonOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place solution and project in the same folder.
        /// </summary>
        internal static string CheckBoxProjectInRoot {
            get {
                return ResourceManager.GetString("CheckBoxProjectInRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Factorio credentials.
        /// </summary>
        internal static string CheckBoxUseFactorioCredentials {
            get {
                return ResourceManager.GetString("CheckBoxUseFactorioCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string CopyItemFromProjectText {
            get {
                return ResourceManager.GetString("CopyItemFromProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string CutItemFromProjectText {
            get {
                return ResourceManager.GetString("CutItemFromProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string DependencyPropertiesFromProjectText {
            get {
                return ResourceManager.GetString("DependencyPropertiesFromProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Project FIle.
        /// </summary>
        internal static string EditProjectFileFromProjectText {
            get {
                return ResourceManager.GetString("EditProjectFileFromProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclude.
        /// </summary>
        internal static string ExcludeItemFromProjectText {
            get {
                return ResourceManager.GetString("ExcludeItemFromProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorio Log.
        /// </summary>
        internal static string FactorioLogOutputTitle {
            get {
                return ResourceManager.GetString("FactorioLogOutputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorio Modification.
        /// </summary>
        internal static string FactorioModificationFile {
            get {
                return ResourceManager.GetString("FactorioModificationFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Factorio Modification.
        /// </summary>
        internal static string FactorioModificationText {
            get {
                return ResourceManager.GetString("FactorioModificationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorio Modification.
        /// </summary>
        internal static string FactorioModificationToolTip {
            get {
                return ResourceManager.GetString("FactorioModificationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorio Standard Output.
        /// </summary>
        internal static string FactorioStandardOutputTitle {
            get {
                return ResourceManager.GetString("FactorioStandardOutputTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _FactrIDE Solution.
        /// </summary>
        internal static string FactrIDESolutionText {
            get {
                return ResourceManager.GetString("FactrIDESolutionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactrIDE Solution.
        /// </summary>
        internal static string FactrIDESolutionToolTip {
            get {
                return ResourceManager.GetString("FactrIDESolutionToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled.
        /// </summary>
        internal static string FileNewUntitled {
            get {
                return ResourceManager.GetString("FileNewUntitled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string FileOpenCommandText {
            get {
                return ResourceManager.GetString("FileOpenCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        internal static string FileRecentCommandText {
            get {
                return ResourceManager.GetString("FileRecentCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists!.
        /// </summary>
        internal static string ItemAlreadyExists {
            get {
                return ResourceManager.GetString("ItemAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Lua_Mode {
            get {
                object obj = ResourceManager.GetObject("Lua_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lua File.
        /// </summary>
        internal static string LuaFile {
            get {
                return ResourceManager.GetString("LuaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactrIDE.
        /// </summary>
        internal static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Item.
        /// </summary>
        internal static string NewItemWindowTitle {
            get {
                return ResourceManager.GetString("NewItemWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        internal static string NewProjectWindowTitle {
            get {
                return ResourceManager.GetString("NewProjectWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string OpenDependencyCommandText {
            get {
                return ResourceManager.GetString("OpenDependencyCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder in File Explorer.
        /// </summary>
        internal static string OpenFolderInProjectText {
            get {
                return ResourceManager.GetString("OpenFolderInProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string PasteItemFromProjectText {
            get {
                return ResourceManager.GetString("PasteItemFromProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter item name.
        /// </summary>
        internal static string PleaseEnterItemNameText {
            get {
                return ResourceManager.GetString("PleaseEnterItemNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter project name.
        /// </summary>
        internal static string PleaseEnterProjectNameText {
            get {
                return ResourceManager.GetString("PleaseEnterProjectNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Compatible.
        /// </summary>
        internal static string ProjectDependencyNotCompatibleText {
            get {
                return ResourceManager.GetString("ProjectDependencyNotCompatibleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        internal static string ProjectDependencyOptionalText {
            get {
                return ResourceManager.GetString("ProjectDependencyOptionalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string ProjectDependencyRequiredText {
            get {
                return ResourceManager.GetString("ProjectDependencyRequiredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        internal static string ProjectDependencyText {
            get {
                return ResourceManager.GetString("ProjectDependencyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProjectRootDirectoryNotExistText.
        /// </summary>
        internal static string ProjectRootDirectoryNotExistText {
            get {
                return ResourceManager.GetString("ProjectRootDirectoryNotExistText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string RemoveDependencyFromProjectText {
            get {
                return ResourceManager.GetString("RemoveDependencyFromProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string RemoveFileCommandText {
            get {
                return ResourceManager.GetString("RemoveFileCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string RemoveFolderCommandText {
            get {
                return ResourceManager.GetString("RemoveFolderCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string RemoveItemFromProjectText {
            get {
                return ResourceManager.GetString("RemoveItemFromProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        internal static string RenameItemFromProjectText {
            get {
                return ResourceManager.GetString("RenameItemFromProjectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Run Factorio.
        /// </summary>
        internal static string RunFactorioCommandText {
            get {
                return ResourceManager.GetString("RunFactorioCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Factorio.
        /// </summary>
        internal static string RunFactorioCommandToolTip {
            get {
                return ResourceManager.GetString("RunFactorioCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveEmptyCommandText {
            get {
                return ResourceManager.GetString("SaveEmptyCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SaveEmptyCommandToolTip {
            get {
                return ResourceManager.GetString("SaveEmptyCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project.
        /// </summary>
        internal static string SaveProjectCommandText {
            get {
                return ResourceManager.GetString("SaveProjectCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SaveProjectCommandToolTip {
            get {
                return ResourceManager.GetString("SaveProjectCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Solution.
        /// </summary>
        internal static string SaveSolutionCommandText {
            get {
                return ResourceManager.GetString("SaveSolutionCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SaveSolutionCommandToolTip {
            get {
                return ResourceManager.GetString("SaveSolutionCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Discord Rich Presence.
        /// </summary>
        internal static string SettingsEnableDiscordRichPresence {
            get {
                return ResourceManager.GetString("SettingsEnableDiscordRichPresence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorio non Steam path:.
        /// </summary>
        internal static string SettingsFactorioNonSteamFolderPath {
            get {
                return ResourceManager.GetString("SettingsFactorioNonSteamFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discord.
        /// </summary>
        internal static string SettingsPageDiscord {
            get {
                return ResourceManager.GetString("SettingsPageDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string SettingsPageDiscordGeneral {
            get {
                return ResourceManager.GetString("SettingsPageDiscordGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorio.
        /// </summary>
        internal static string SettingsPageFactorio {
            get {
                return ResourceManager.GetString("SettingsPageFactorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string SettingsPageFactorioGeneral {
            get {
                return ResourceManager.GetString("SettingsPageFactorioGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorio Mod Portal.
        /// </summary>
        internal static string SettingsPageFactorioModPortal {
            get {
                return ResourceManager.GetString("SettingsPageFactorioModPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting.
        /// </summary>
        internal static string SettingsPageReporting {
            get {
                return ResourceManager.GetString("SettingsPageReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Application exceptions via Web to developers.
        /// </summary>
        internal static string SettingsReportToWeb {
            get {
                return ResourceManager.GetString("SettingsReportToWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run via Steam.
        /// </summary>
        internal static string SettingsRunFactorioViaSteamLink {
            get {
                return ResourceManager.GetString("SettingsRunFactorioViaSteamLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FactrIDE Solution.
        /// </summary>
        internal static string SolutionText {
            get {
                return ResourceManager.GetString("SolutionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Stop Factorio.
        /// </summary>
        internal static string StopFactorioCommandText {
            get {
                return ResourceManager.GetString("StopFactorioCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Factorio.
        /// </summary>
        internal static string StopFactorioCommandToolTip {
            get {
                return ResourceManager.GetString("StopFactorioCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location:.
        /// </summary>
        internal static string TextBlockLocation {
            get {
                return ResourceManager.GetString("TextBlockLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string TextBlockPassword {
            get {
                return ResourceManager.GetString("TextBlockPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name:.
        /// </summary>
        internal static string TextBlockProjectName {
            get {
                return ResourceManager.GetString("TextBlockProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution name:.
        /// </summary>
        internal static string TextBlockSolutionName {
            get {
                return ResourceManager.GetString("TextBlockSolutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username:.
        /// </summary>
        internal static string TextBlockUsername {
            get {
                return ResourceManager.GetString("TextBlockUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Factorio Log.
        /// </summary>
        internal static string ViewFactorioLogOutputCommandText {
            get {
                return ResourceManager.GetString("ViewFactorioLogOutputCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorio Log.
        /// </summary>
        internal static string ViewFactorioLogOutputCommandToolTip {
            get {
                return ResourceManager.GetString("ViewFactorioLogOutputCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Factorio Modification Log.
        /// </summary>
        internal static string ViewFactorioModOutputCommandText {
            get {
                return ResourceManager.GetString("ViewFactorioModOutputCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorio Modification Log.
        /// </summary>
        internal static string ViewFactorioModOutputCommandToolTip {
            get {
                return ResourceManager.GetString("ViewFactorioModOutputCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Factorio Standard Output.
        /// </summary>
        internal static string ViewFactorioStandardOutputCommandText {
            get {
                return ResourceManager.GetString("ViewFactorioStandardOutputCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorio Standard Output.
        /// </summary>
        internal static string ViewFactorioStandardOutputCommandToolTip {
            get {
                return ResourceManager.GetString("ViewFactorioStandardOutputCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Solution Explorer.
        /// </summary>
        internal static string ViewProjectExplorerCommadText {
            get {
                return ResourceManager.GetString("ViewProjectExplorerCommadText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Explorer.
        /// </summary>
        internal static string ViewProjectExplorerCommandToolTip {
            get {
                return ResourceManager.GetString("ViewProjectExplorerCommandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string ViewProjectPropertiesCommandText {
            get {
                return ResourceManager.GetString("ViewProjectPropertiesCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string ViewSolutionPropertiesCommandText {
            get {
                return ResourceManager.GetString("ViewSolutionPropertiesCommandText", resourceCulture);
            }
        }
    }
}
